FROM alpine

EXPOSE 12345/tcp

RUN apk add luajit lua-sec lua-socket lua-filesystem lua5.1-copas tor
COPY torrc /app/
RUN sed -i 's/HiddenServiceDir ./HiddenServiceDir \/app/' /app/torrc
COPY src /app/src

WORKDIR /app
VOLUME /app/hidden_service

CMD chmod 700 /app/hidden_service && tor -f /app/torrc --runasdaemon 1 && \
  luajit /app/src/trainer.lua
