FROM alpine

RUN apk add torsocks tor luajit lua5.1-sec lua5.1-socket
COPY scripts/test_rattata.lua /app/

WORKDIR /app
VOLUME /app/hidden_service

CMD tor --runasdaemon 1 && \
  torsocks luajit /app/test_rattata.lua $(cat /app/hidden_service/hostname)
