FROM alpine

EXPOSE 12345/tcp

RUN apk add tor luajit lua5.1-copas lua5.1-sec lua5.1-socket lua5.1-penlight lua5.1-filesystem
COPY torrc /app/
RUN sed -i 's/HiddenServiceDir ./HiddenServiceDir \/app/' /app/torrc
COPY src /app/src
COPY eggs /app/eggs

WORKDIR /app
VOLUME /app/hidden_service

CMD chmod 700 /app/hidden_service && tor -f /app/torrc --runasdaemon 1 && \
  luajit /app/src/trainer.lua
